---
- name: Perform initial host setup
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Wait for hosts to come online
      wait_for_connection:
        timeout: 800
    - name: Test echo on all machines
      shell: |
        echo "Hello, world!"
    - name: Install apt pkgs
      apt:
        upgrade: yes
        update_cache: yes
        pkg:
        - git
        - libblas3
        - liblapack3
        - liblapack-dev
        - libblas-dev
        - gfortran
        - libatlas-base-dev
        - python3-pip
        - build-essential
        - libssl-dev
        - libffi-dev
        - python3-dev
        - liblz4-dev
        - libunwind-dev
        - wget
