---
- name: Perform initial host setup
  hosts: all
  become: yes
  gather_facts: false
  tasks:
  - name: Wait for hosts to come online
    wait_for_connection:
      timeout: 800
  - name: Test echo on all machines
    shell: |
      echo "Hello, world!"
